# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:

  entryNode: # This node is the network entry node
    image: kadlab:latest
    stdin_open: true
    tty: true
    ports:
      - "8001:80"
    networks:
      kademlia_network:
        ipv4_address: 172.20.0.10
    container_name: entryNode

  node: # These nodes join the network through the entry node
    image: kadlab:latest # Make sure your Docker image has this name.
    depends_on:
      - entryNode
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 49
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - ":80"
    networks:
      - kademlia_network
      
networks:
  kademlia_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

