name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get -y install sshpass

    - name: SSH into Server and remove old code
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 27001 martinaskolin@130.240.207.20 << EOF
          sudo rm -r D7024E-Group-3
        EOF
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Copy Code to Server
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no -r -P 27001 $GITHUB_WORKSPACE/ martinaskolin@130.240.207.20:/home/martinaskolin/
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: SSH into Server and Execute Docker Commands
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 27001 martinaskolin@130.240.207.20 << EOF
          cd D7024E-Group-3

          # Step 1: Remove all containers
          sudo docker rm entryNode -f
          sudo docker rm d7024e-group-3-node-1 -f
          sudo docker rm d7024e-group-3-node-2 -f
          sudo docker rm d7024e-group-3-node-3 -f
          sudo docker rm d7024e-group-3-node-4 -f
          sudo docker rm d7024e-group-3-node-5 -f
          sudo docker rm d7024e-group-3-node-6 -f
          sudo docker rm d7024e-group-3-node-7 -f
          sudo docker rm d7024e-group-3-node-8 -f
          sudo docker rm d7024e-group-3-node-9 -f
          sudo docker rm d7024e-group-3-node-10 -f
          sudo docker rm d7024e-group-3-node-11 -f
          sudo docker rm d7024e-group-3-node-12 -f
          sudo docker rm d7024e-group-3-node-13 -f
          sudo docker rm d7024e-group-3-node-14 -f
          sudo docker rm d7024e-group-3-node-15 -f
          sudo docker rm d7024e-group-3-node-16 -f
          sudo docker rm d7024e-group-3-node-17 -f
          sudo docker rm d7024e-group-3-node-18 -f
          sudo docker rm d7024e-group-3-node-19 -f
          sudo docker rm d7024e-group-3-node-20 -f
          sudo docker rm d7024e-group-3-node-21 -f
          sudo docker rm d7024e-group-3-node-22 -f
          sudo docker rm d7024e-group-3-node-23 -f
          sudo docker rm d7024e-group-3-node-24 -f
          sudo docker rm d7024e-group-3-node-25 -f
          sudo docker rm d7024e-group-3-node-26 -f
          sudo docker rm d7024e-group-3-node-27 -f
          sudo docker rm d7024e-group-3-node-28 -f
          sudo docker rm d7024e-group-3-node-29 -f
          sudo docker rm d7024e-group-3-node-30 -f
          sudo docker rm d7024e-group-3-node-31 -f
          sudo docker rm d7024e-group-3-node-32 -f
          sudo docker rm d7024e-group-3-node-33 -f
          sudo docker rm d7024e-group-3-node-34 -f
          sudo docker rm d7024e-group-3-node-35 -f
          sudo docker rm d7024e-group-3-node-36 -f
          sudo docker rm d7024e-group-3-node-37 -f
          sudo docker rm d7024e-group-3-node-38 -f
          sudo docker rm d7024e-group-3-node-39 -f
          sudo docker rm d7024e-group-3-node-40 -f
          sudo docker rm d7024e-group-3-node-41 -f
          sudo docker rm d7024e-group-3-node-42 -f
          sudo docker rm d7024e-group-3-node-43 -f
          sudo docker rm d7024e-group-3-node-44 -f
          sudo docker rm d7024e-group-3-node-45 -f
          sudo docker rm d7024e-group-3-node-46 -f
          sudo docker rm d7024e-group-3-node-47 -f
          sudo docker rm d7024e-group-3-node-48 -f
          sudo docker rm d7024e-group-3-node-49 -f

          # Step 2: Remove the old image
          sudo docker image rm kadlab -f

          # Step 3: Remove all unused images
          sudo docker image prune -f

          # Step 4: Build the new Docker image
          sudo docker build . -t kadlab

          # Step 5: Deploy the Docker containers using the updated docker-compose.yml
          sudo docker compose up -d
        EOF
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
